const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const mysql = require('mysql');
const productos = require('./controllers/productosRouter');
const usuarios = require('./controllers/usuariosRouter');
const cupones = require('./controllers/cuponesDescuentoRouter');
const retos = require('./controllers/retosRouter');
const mesas = require('./controllers/mesaRouter');
const pedidos = require('./controllers/pedidosRouter');
const valoraciones = require('./controllers/valoracionRouter');
const login = require('./controllers/loginRouter');

const connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'root',
  database : 'smashdb'
});

connection.connect(function(err) {
  if(err) throw err;
  var queries = ["DROP TABLE IF EXISTS UsuarioPrincipal;",
                "DROP TABLE IF EXISTS Tarjeta;",
                "DROP TABLE IF EXISTS Valoracion;",
                "DROP TABLE IF EXISTS ProductoPedido;",
                "DROP TABLE IF EXISTS PedidoComida;",
                "DROP TABLE IF EXISTS Direccion;",
                "DROP TABLE IF EXISTS Mesa;",                
                "DROP TABLE IF EXISTS CuponDescuento;",
                "DROP TABLE IF EXISTS ProductoOfertado;",
                "DROP TABLE IF EXISTS Menu;",
                "DROP TABLE IF EXISTS Usuario;",
                "DROP TABLE IF EXISTS Paso;",
                "DROP TABLE IF EXISTS Solucion;",
                "DROP TABLE IF EXISTS Pista;",
                "DROP TABLE IF EXISTS Reto;",
                "CREATE TABLE UsuarioPrincipal (usuarioId INT NOT NULL, tipo ENUM('ADMIN','NO ADMIN') NOT NULL, token VARCHAR(100) NOT NULL, fechaLogin BIGINT NOT NULL)",
                "CREATE TABLE Usuario (id INT AUTO_INCREMENT, username VARCHAR(50) NOT NULL, nombre VARCHAR(255) NOT NULL, correo VARCHAR(100) NOT NULL, contrasena VARCHAR(255) NOT NULL, telefono INT, tipo ENUM('ADMIN','NO ADMIN') NOT NULL DEFAULT 'NO ADMIN', creditoDigital FLOAT DEFAULT 0.0, PRIMARY KEY(id));",
                "CREATE TABLE Tarjeta (id INT AUTO_INCREMENT, numero VARCHAR(20) NOT NULL, expiracion DATE NOT NULL, usuarioId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE);",
                "CREATE TABLE Direccion (id INT AUTO_INCREMENT, nombreDireccion VARCHAR(50) NOT NULL, direccion VARCHAR(200) NOT NULL, pais VARCHAR(50) NOT NULL, ciudad VARCHAR(100) NOT NULL, usuarioId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE);",
                "CREATE TABLE CuponDescuento (id INT AUTO_INCREMENT, codigo VARCHAR(255) NOT NULL, porcentaje INT NOT NULL, PRIMARY KEY(id));",
                "CREATE TABLE PedidoComida (id INT AUTO_INCREMENT, metodoPago ENUM('Tarjeta','Cartera digital'), fecha DATE NOT NULL, hora TIME NOT NULL, estado ENUM('Pagado','En preparacion','En transito','Entregado') DEFAULT 'Pagado', nombreDireccion VARCHAR(50) NOT NULL, usuarioId INT NOT NULL, direccionUsuarioId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE, FOREIGN KEY(direccionUsuarioId) REFERENCES Direccion(id) ON DELETE CASCADE);",
                "CREATE TABLE Menu (id INT AUTO_INCREMENT, nombre VARCHAR(100) NOT NULL, descripcion TEXT NOT NULL, precio FLOAT, PRIMARY KEY(id));",
                "CREATE TABLE ProductoOfertado (id INT AUTO_INCREMENT, nombre VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, imagen TEXT NOT NULL, precio FLOAT NOT NULL, tipo ENUM('Entremes','Plato','Postre','Bebida') NOT NULL, attr INT, menuId INT, PRIMARY KEY(id), FOREIGN KEY (menuId) REFERENCES Menu(id));",
                "CREATE TABLE ProductoPedido (id INT AUTO_INCREMENT, cantidad INT NOT NULL, pedidoId INT NOT NULL, productoOfertadoId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (pedidoId) REFERENCES PedidoComida(id) ON DELETE CASCADE, FOREIGN KEY (productoOfertadoId) REFERENCES ProductoOfertado(id) ON DELETE CASCADE);",
                "CREATE TABLE Valoracion (id INT AUTO_INCREMENT, puntuacion INT NOT NULL, resenya TEXT, nombreUsuario VARCHAR(50) NOT NULL, nombreProducto VARCHAR(255) NOT NULL, usuarioId INT NOT NULL, productoPedidoId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE, FOREIGN KEY (productoPedidoId) REFERENCES ProductoPedido(id) ON DELETE CASCADE);",
                "CREATE TABLE Mesa (id INT AUTO_INCREMENT, numeroPersonas INT NOT NULL, fecha DATE NOT NULL, hora TIME NOT NULL, precioDescuento FLOAT, usuarioId INT NOT NULL, menuId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE, FOREIGN KEY (menuId) REFERENCES Menu(id));",
                "CREATE TABLE Reto (id INT AUTO_INCREMENT, nombre VARCHAR(30) NOT NULL, descripcion VARCHAR(255) NOT NULL, categoria ENUM('Inyeccion de codigo','Autenticacion e identificacion','Control de acceso','Validacion indebida','Criptografía') NOT NULL, dificultad INT NOT NULL, completado BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(id));",
                "CREATE TABLE Solucion (id INT AUTO_INCREMENT, nombre VARCHAR(50) NOT NULL, tipo ENUM('Interactiva','No interactiva') NOT NULL, retoId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (retoId) REFERENCES Reto(id));",
                "CREATE TABLE Pista (id INT AUTO_INCREMENT, pista VARCHAR(50) NOT NULL, retoId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (retoId) REFERENCES Reto(id));",
                "CREATE TABLE Paso (id INT AUTO_INCREMENT, numero INT NOT NULL, solucion TEXT NOT NULL, solucionId INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (solucionId) REFERENCES Solucion(id));",
                "INSERT INTO Menu (id,nombre, descripcion) VALUES (1,'Sin menú','Los comensales pedirán a la carta')",
                "INSERT INTO Menu (id,nombre, descripcion, precio) VALUES (2,'Mediterraneo','Menu de la dieta mediterranea', 15.6)",
                "INSERT INTO Menu (id,nombre, descripcion, precio) VALUES (3,'Asiatico','Menu de la dieta asiatica', 30.5)",
                "INSERT INTO Menu (id,nombre, descripcion, precio) VALUES (4,'Menú completo','Menú de hamburguesa completa, patatas fritas y refresco',10.0)",
                "INSERT INTO Menu (id,nombre, descripcion, precio) VALUES (5,'Menú italiano','Menú clásico de Italia',18.8)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Hamburguesa especial', 'Hamburguesa con queso, lechuga, tomate y cebolla',4.5,'https://cdn-icons-png.flaticon.com/512/883/883517.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Pizza', 'Pizza con base de tomate, mozzarella y bacon',8.0,'https://cdn-icons-png.flaticon.com/512/1404/1404945.png','Plato',5)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Perrito caliente', 'Perrito caliente clásico con ketchup y patatas',2.5,'https://cdn-icons-png.flaticon.com/512/3845/3845161.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Ensalada', 'Ensalada mixta',4.5,'https://cdn-icons-png.flaticon.com/512/1057/1057510.png','Entremes',2)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Hamburguesa completa', 'Hamburguesa de buey con lechuga, tomate, cebolla y queso',7.0,'https://cdn-icons-png.flaticon.com/512/267/267873.png','Plato',4)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Sopa', 'Sopa caliente de pollo con fideos',4.0,'https://cdn-icons-png.flaticon.com/512/3823/3823394.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Churrasco', 'Churrasco de cerdo con patatas fritas de guarnición',6.8,'https://cdn-icons-png.flaticon.com/512/5854/5854405.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Té frío', 'Té de frutas del bosque con hielo',2.0,'https://cdn-icons-png.flaticon.com/512/8088/8088125.png','Bebida',3)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Sushi', 'Plato de sushi combinado',9.0,'https://cdn-icons-png.flaticon.com/512/6920/6920151.png','Plato',3)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Alitas de pollo', 'Cubo de alitas de pollo fritas',8.0,'https://cdn-icons-png.flaticon.com/512/6611/6611751.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Espaguetis', 'Espaguettis italianos a la boloñesa',6.5,'https://cdn-icons-png.flaticon.com/512/3823/3823096.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Chelitas de cordero', 'Chuletas de cordero a la brasa',10.0,'https://cdn-icons-png.flaticon.com/512/4802/4802503.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Burrito mejicano', 'Tortilla de trigo enrollada en rellena de lechuga, aguacate, pollo y frijoles',5.0,'https://cdn-icons-png.flaticon.com/512/6981/6981359.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Taco mejicano', 'Carne de ternera o de pollo con tomate, cebolla y guacamole en una tortilla de maíz',5.0,'https://cdn-icons-png.flaticon.com/512/4062/4062916.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Patatas fritas', 'Patatas naturales fritas',1.5,'https://cdn-icons-png.flaticon.com/512/1046/1046786.png','Entremes',4)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Nachos con guacamole', 'Triángulos de tortilla de maíz fritos con queso y guacamole',7.0,'https://cdn-icons-png.flaticon.com/512/5596/5596725.png','Entremes')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Churros con chocolate', 'Masa de agua, harina, aceite y sal frita',2.0,'https://cdn-icons-png.flaticon.com/512/7433/7433816.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Huevos revueltos', 'Revuelto de huevo con gambas, espárragos y tacos de jamón',6.5,'https://cdn-icons-png.flaticon.com/512/1814/1814189.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Paella', 'Arroz con marisco',6.0,'https://cdn-icons-png.flaticon.com/512/4900/4900654.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Salmón', 'Salmón cocinado a la plancha',10.0,'https://cdn-icons-png.flaticon.com/512/988/988911.png','Plato',3)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Tarta de queso', 'Tarta de queso con mermelada de frambuesa',3.5,'https://cdn-icons-png.flaticon.com/512/4771/4771563.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Pollo asado', 'Pollo al carbón',7.0,'https://cdn-icons-png.flaticon.com/512/1046/1046802.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Sandwich', 'Sandwich mixto, queso y jamon cocido',2.0,'https://cdn-icons-png.flaticon.com/512/1033/1033228.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Empanadas', 'Masa de pan rellena de atún y tomate',4.3,'https://cdn-icons-png.flaticon.com/512/5100/5100421.png','Entremes')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Cóctel', 'Mezcla de diferentes bebidas',3.8,'https://cdn-icons-png.flaticon.com/512/8078/8078904.png','Entremes')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Café', 'Café al gusto, solo, con leche, cortado',1.5,'https://cdn-icons-png.flaticon.com/512/4566/4566425.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Aliño de pulpo', 'Ensalada de cebolla, tomate, pimiento y pulto aliñada con aceite y vinagre',3.6,'https://cdn-icons-png.flaticon.com/512/6433/6433380.png','Entremes')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Helado de fresa', 'Helado con fresas naturales',2.8,'https://cdn-icons-png.flaticon.com/512/3409/3409647.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Refresco', 'Gaseosa a elegir',1.0,'https://cdn-icons-png.flaticon.com/512/1046/1046782.png','Bebida',4)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Kebap', 'Auténtico kebap turco con carne de ternera y pollo, salsa yogur y picante y lechuga, tomate y cebolla',5.4,'https://cdn-icons-png.flaticon.com/512/706/706856.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Lasaña', 'Láminas de pasta superpuestas con relleno de carne de ternera, queso y tomate',6.1,'https://cdn-icons-png.flaticon.com/512/6785/6785760.png','Plato',5)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Bocadillo', 'Bocadillo de jamón ibérico',6.3,'https://cdn-icons-png.flaticon.com/512/5508/5508486.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Pancakes', 'Masa de harina, huevo, leche y aceite con sirope de caramento',3.2,'https://cdn-icons-png.flaticon.com/512/135/135561.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Gambas cocidas', 'Gambas de Huelva al puñao',12.0,'https://cdn-icons-png.flaticon.com/512/7430/7430044.png','Entremes',2)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Cerveza', 'Cerveza casera',2.0,'https://cdn-icons-png.flaticon.com/512/931/931949.png','Bebida')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Tarta de chocolate', 'Tarta con galleta y natilla de chocolate',3.0,'https://cdn-icons-png.flaticon.com/512/3565/3565217.png','Postre',2)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Helado de chocolate', 'Helado de chocolate',10.0,'https://cdn-icons-png.flaticon.com/512/8060/8060536.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Copa de vino', 'Copa de vino Rioja',2.5,'https://cdn-icons-png.flaticon.com/512/850/850207.png','Bebida')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Pechuga de pollo empanada', 'Pechuga de pollo con rebozado frita',4.0,'https://cdn-icons-png.flaticon.com/512/8043/8043419.png','Plato')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Batido de fresa', 'Batido casero de fresas',3.1,'https://cdn-icons-png.flaticon.com/512/5912/5912107.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo) VALUES ('Flan de huevo', 'Flan de huevo con base de caramelo',2.5,'https://cdn-icons-png.flaticon.com/512/7397/7397545.png','Postre')",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Risotto', 'Arroz meloso con caldo de pollo y champiñones',9.5,'https://cdn-icons-png.flaticon.com/512/135/135640.png','Plato',5)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Gazpacho', 'Sopa de tomate, pepino, cebolla, agua, vinagre',3.7,'https://cdn-icons-png.flaticon.com/512/6938/6938398.png','Entremes',2)",
                "INSERT INTO ProductoOfertado (nombre,descripcion,precio,imagen,tipo,menuId) VALUES ('Solomillo de ternera', 'Solomillo de vaca vieja a la brasa',15.8,'https://cdn-icons-png.flaticon.com/512/2114/2114716.png','Plato',2)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,creditoDigital) VALUES ('perico','Pepe Rico','perico@gmail.com','asd1234','666777888',20.5)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,tipo,creditoDigital) VALUES ('josrompoz1','Jose Carlos','josrompoz1@gmail.com','qwerty','654654654','ADMIN',10000)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono) VALUES ('aitor','aitortilla','aitortilla@gmail.com','asd1234','653780421')",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,tipo,creditoDigital) VALUES ('admin','Administrador Smash&Eat Me','admin1@gmail.com','password','678090090','ADMIN',10000)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,tipo,creditoDigital) VALUES ('user5','Usuario Cinco','user5@gmail.com','bgrtgj45','613097632','NO ADMIN',0)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,tipo,creditoDigital) VALUES ('user6','Usuario Seis','user6@gmail.com','56jmyuer','657832789','NO ADMIN',0)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,tipo,creditoDigital) VALUES ('user7','Usuario Siete','user7@gmail.com','htr23fgjm','624795522','NO ADMIN',200)",
                "INSERT INTO Usuario (username,nombre,correo,contrasena,telefono,tipo,creditoDigital) VALUES ('user8','Usuario Ocho','user8@gmail.com','515546erggre','758596230','NO ADMIN',0)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('55554444333322221111','2025-05-01',1)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('55554444333311112222','2026-09-01',1)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('42424242424242424242','2028-05-01',2)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('55448562186335235953','2026-02-12',3)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('39519684320084600000','2023-12-25',4)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('20651984660354984665','2022-01-31',4)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('54160698498630256252','2025-10-21',5)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('00521651698958165120','2024-07-04',6)",
                "INSERT INTO Tarjeta (numero, expiracion, usuarioId) VALUES ('51960984952006984565','2027-04-29',7)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Mi casa','C/ Rodrigo, 2','España','Sevilla',1)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Campo','C/ España, 23','España','Malaga',1)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Casa abuela','C/ Oriente, 78','España','Granada',2)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Mi casa','C/ Tipo Pepe, 20','España','Almeria',3)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Casa Antonio','C/ Patin, 1','España','Cadiz',4)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Casa suegro','C/ Morillo, 65','España','Huelva',5)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Casa abuelo','C/ Ronda del Sur, 788','España','Jaen',6)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Mi casa','C/ Ronda de Oriente, 23','España','Sevilla',7)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Casa playa','C/ Adriano, 124','España','Sevilla',8)",
                "INSERT INTO Direccion (nombreDireccion, direccion, pais, ciudad, usuarioId) VALUES ('Mi casa','C/ Avenida, 56','España','Sevilla',8)",
                "INSERT INTO CuponDescuento (codigo, porcentaje) VALUES ('semotoño',15)",
                "INSERT INTO CuponDescuento (codigo, porcentaje) VALUES ('semverano',5)",
                "INSERT INTO CuponDescuento (codigo, porcentaje) VALUES ('seminvierno',10)",
                "INSERT INTO CuponDescuento (codigo, porcentaje) VALUES ('semprimavera',10)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (1, 'Login', 'Inicia la sesión del usuario ''perico'' sin conocer su contraseña', 'Inyeccion de codigo', 1)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (2, 'XSS reflejado', 'Realiza un ataque XSS reflejado', 'Inyeccion de codigo', 1)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (3, 'Cookies de usuario', 'Muestra las cookies de un usuario cuando este acceda a su cuenta e interactúe con la aplicación', 'Inyeccion de codigo', 3)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (4, 'Valoración de 0', 'Realiza una valoración de 0 puntos', 'Validacion indebida', 2)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (5, 'Usuario ADMIN', 'Registra un usuario con permisos de administración', 'Validacion indebida', 2)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (6, 'Ver pedidos', 'Mira los pedidos realizados por otro usuario', 'Control de acceso', 2)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (7, 'Pedido ajeno', 'Realiza un pedido con la sesión de otro usuario', 'Control de acceso', 3)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (8, 'Reseña 5 estrellas', 'Elimina valoraciones existentes con 5 estrellas', 'Control de acceso', 3)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (9, 'Cupón 100%', 'Crea un cupón de descuento del 100% y realiza un pedido solo con costes de envío', 'Control de acceso', 4)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (10, 'Fuerza bruta', 'Accede a la cuenta de un usuario administrador probando contraseñas comunes', 'Autenticacion e identificacion', 2)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (11, 'Cambia contraseña', 'Cambia la contraseña de un usuario administrador para que no tenga acceso a su cuenta', 'Autenticacion e identificacion', 4)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (13, 'Credenciales', 'Consigue todos los usuarios y contraseñas de la aplicación e inicia sesión con el usuario cuyo ID sea 7', 'Inyeccion de codigo', 5)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (14, 'Visualiza una contraseña', 'Después de iniciar sesión con el usuario ''perico'', visualiza su contraseña e inicia sesión con sus credenciales', 'Criptografía', 3)",
                "INSERT INTO Reto (id, nombre, descripcion, categoria, dificultad) VALUES (15, 'Rol ADMIN', 'Cambia el rol de un usuario a administrador', 'Validacion indebida', 4)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Realiza un ataque tipo inyección SQL común',1)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Utiliza la etiqueta iframe en un ataque XSS',2)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Busca un input donde haya que introducir una URL',3)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Utiliza las herramientas para desarrollador',4)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Intenta cambiar el valor del readonly',5)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Cambia algún dato del ''Session Storage''',6)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Cambia algún dato del ''Session Storage''',7)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Cambia algún dato del ''Session Storage''',8)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Conviertete en usuario ADMIN',9)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Prueba usuarios/contraseñas comunes',10)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Cambia algún dato del ''Session Storage''',11)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Ataque tipo UNION SQL',13)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Cambia el valor del tipo de input',14)",
                "INSERT INTO Pista (pista, retoId) VALUES ('Utiliza las herramientas para desarrollador',15)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (1, 'Interactiva', 'Solucion 1', 1)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (2, 'No interactiva', 'Solucion 2', 1)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (3, 'Interactiva', 'Solucion 1', 13)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (4, 'No interactiva', 'Solucion 2', 13)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (5, 'Interactiva', 'Solucion 1', 6)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (6, 'Interactiva', 'Solucion 1', 7)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (7, 'Interactiva', 'Solucion 1', 8)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (8, 'Interactiva', 'Solucion 1', 9)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (9, 'No interactiva', 'Solucion 1', 10)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (10, 'Interactiva', 'Solucion 1', 11)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (11, 'Interactiva', 'Solucion 1', 14)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (13, 'Interactiva', 'Solucion 1', 4)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (14, 'Interactiva', 'Solucion 1', 5)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (15, 'No interactiva', 'Solucion 1', 15)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (16, 'Interactiva', 'Solucion 1', 2)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (17, 'Interactiva', 'Solucion 1', 3)",
                "INSERT INTO Solucion (id, tipo, nombre, retoId) VALUES (18, 'No interactiva', 'Solucion 2', 15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Accede a la vista de login',1)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Introduce ''perico'' en el campo nombre de usuario',1)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En el campo contraseña, introduce código SQL para intentar acceder a la sesión',1)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'El código SQL tiene que ser algo parecido a: '' OR ''1''=''1',1)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Accede a la vista de login',2)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'En el campo nombre de usuario, introduce ''perico''',2)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En el campo contraseña, introduce código SQL: '' OR ''b''=''b',2)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Realizaremos un ataque mediante el comando SQL ''UNION''',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Para ello, abriremos una nueva ventana del navegador',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Los ataques UNION se caracterizan por unir dos tablas con el mismo número de columnas. En caso de que no tengan el mismo número, podemos seleccionar columnas con valor null. Por ello, hay que conocer cuántas columnas tienen las tablas ProductoOfertado y Usuario',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Realizaremos una llamada al endpoint ''/productos/tipo/'' del servidor con el tipo de producto a filtar más el comando UNION',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'La query sería: Bebida'' UNION SELECT null FROM Usuario;-- . Hay que tener en cuenta los caracteres especiales en las URL (https://www.w3schools.com/tags/ref_urlencode.ASP)',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (6,'Repetimos la llamada añadiendo ''null'' hasta que el servidor nos de una respuesta valida',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (7,'Cada tabla tiene un total de 8 columnas. Como queremos conocer el nombre de usuario y la contraseña de todos los usuarios del sistema, la URL final sería: ''http://localhost:8080/productos/tipo/Bebida'' UNION SELECT null,null,null,null,null,null,username,contrasena FROM Usuario;--'' (teniendo en cuenta los caracteres especiales)',3)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Realizaremos un ataque mediante el comando SQL ''UNION''',4)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Para ello, abriremos una nueva ventana del navegador',4)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Los ataques UNION se caracterizan por unir dos tablas con el mismo número de columnas. En caso de que no tengan el mismo número, podemos seleccionar columnas con valor null. En este caso, las tablas ProductoOfertado y Usuario tienen el mismo número de columnas',4)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Por lo tanto, podemos realizar la llamada al servidor: ''http://localhost:8080/productos/tipo/Postre'' UNION SELECT * FROM Usuario;--''',4)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'En primer lugar, ve a la página de registro de usuario y añade un nuevo usuario',5)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Inicia sesión con el usuario registrado',5)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Accede al apartado ''Application'' en las herramientas para desarrollador',5)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'En ''Session Storage'' aparecerá un atributo llamado ''usuarioId''. Prueba a cambiar el valor a otro entero numérico, por ejemplo, 1',5)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Si recargas la página y se accede al historial de pedidos se podrán ver todos los pedidos del usuario 1',5)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Inicia sesión con un usuario que conozcas (o crea uno nuevo)',6)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Accede al apartado ''Application'' en las herramientas para desarrollador',6)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En ''Session Storage'' aparecerá un atributo llamado ''usuarioId''. Prueba a cambiar el valor a otro entero numérico, por ejemplo, 1',6)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Accede a los productos y añade productos a la cesta',6)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Sigue los pasos de la cesta para realizar el pedido con el usuario 1',6)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Inicia sesión con un usuario que conozcas (o crea uno nuevo)',7)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'En la aplicación hay dos tipos de usuario: el usuario cliente (''NO ADMIN'') que únicamente puede crear pedidos, valoraciones y reservas, y el usuario administrador (''ADMIN'') que tiene permiso para realizar cualquier acción sobre la aplicación',7)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Accede al apartado ''Application'' en las herramientas para desarrollador',7)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'En ''Session Storage'' aparecerá un atributo llamado ''rol''. Prueba a cambiar el valor a un usuario administrador introduciendo ''ADMIN''',7)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Si accedes al listado de usuarios, verás todas las valoraciones. Elimina alguna/s valoración/es de 5 estrellas',7)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Inicia sesión con un usuario que conozcas (o crea uno nuevo)',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'En la aplicación hay dos tipos de usuario: el usuario cliente (''NO ADMIN'') que únicamente puede crear pedidos, valoraciones y reservas, y el usuario administrador (''ADMIN'') que tiene permiso para realizar cualquier acción sobre la aplicación',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Accede al apartado ''Application'' en las herramientas para desarrollador',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'En ''Session Storage'' aparecerá un atributo llamado ''rol''. Prueba a cambiar el valor a un usuario administrador introduciendo ''ADMIN''',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Recargamos la página (ya tendremos permisos de administrador) y accedemos al listado de cupones de descuento',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (6,'Creamos un cupón del 100% de descuento',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (7,'Cerramos la sesión y volvemos a iniciarla con nuestro usuario',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (8,'Realizamos un pedido con el código recién creado y obtendremos un pedido completamente gratis',8)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Los ataques de fuerza bruta consisten en probar usuarios/contraseñas hasta dar con el acertado',9)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Para completar este reto, podemos utilizar alguna herramienta de ataques de fuerza bruta como THC Hydra, Aircrack-Ng o Ncrack por ejemplo',9)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'También podemos simplemente buscar los usuarios/contraseñas más atacados y probar a mano en el login hasta dar con las credenciales correctas',9)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'En primer lugar, finaliza el reto ''Fuerza bruta'' para acceder a la sesión de un usuario administrador',10)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Accede al perfil de dicho usuario y prueba a cambiar la contraseña',10)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Cierra sesión y vuelve a hacer login con las credenciales antigüas',10)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Ahora, el usuario admin/admin no conoce sus credenciales y no puede iniciar sesión',10)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Primero, finaliza el reto ''Login''.',11)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Cuando estés dentro de la sesión del usuario ''perico'', accede a su perfil de usuario',11)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En las herramientas para desarrollador, en el apartado ''Elements'', busca el código del input de la contraseña. Cambia el valor de ''type'' a text',11)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'La contraseña deberá aparecer al no estar encriptada',11)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Recuerda las credenciales, cierra sesión y vuelve a iniciar sesión.',11)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'En primer lugar, para valorar un producto, el estado del pedido deberá ser ''Entregado''. Por lo tanto, deberemos tener un pedido en dichas condiciones para poder realizar el reto',13)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Accedemos a valorar un producto. Vemos que hay un botón deshabilitado que no deja continuar si la puntuación es 0',13)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Si entramos en las herramienta para desarrollador, inspeccionamos el botón y podremos ver que tiene una propiedad llamada ''disabled''',13)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Si cambiamos el valor de dicha propiedad de ''true'' a ''false'' o simplemente la eliminamos por completo, el aspecto del botón no cambiará pero podremos continuar con la valoración',13)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Ponemos el slider a 0, escribimos una reseña y aceptamos la valoración',13)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Accedemos al registro de usuario',14)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Observamos que existe un input que indica el tipo de usuario y que está en modo solo lectura',14)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'Si entramos en las herramientas para desarrollador e inspeccionamos dicho input, veremos que tiene una propiedad llamada ''readonly''',14)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Si cambiamos el valor de dicha propiedad a ''false'' o simplemente la eliminamos por completo, podremos escribir en el input',14)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'NO ADMIN es para usuarios no administradores y ADMIN para usuarios administradores.',14)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (6,'Ponemos el valor a ADMIN y creamos el usuario rellenando los demás datos',14)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Nos creamos un nuevo usuario',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Iniciamos sesión y accedemos al perfil del usuario',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En el formulario para editar el usuario, vemos un input con el rol que tiene',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Dicho input está en modo readonly',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Si entramos en las herramientas para desarrollador e inspeccionamos dicho input, veremos que tiene una propiedad llamada ''readonly''',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (6,'Si cambiamos el valor de dicha propiedad a ''false'' o simplemente la eliminamos por completo, podremos escribir en el input',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (7,'Ponemos el valor a ADMIN y actualizamos el usuario',15)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Accede al filtro de productos',16)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'En el campo buscar plato, introducimos un script con la etiqueta ''<iframe>''',16)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'<iframe src=''javascript:alert(`xss`)''>',16)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Pulsamos en buscar y aparecerá la alerta javascript',16)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Iniciamos sesión con una cuenta de administrador',17)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Navegamos al formulario para crear un nuevo plato',17)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En el campo URL de la imagen del plato tenemos que introducir un script que coja las cookies del usuario',17)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'javascript:alert(document.cookie);',17)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (5,'Rellenamos los demás campos del formulario y guardamos el plato',17)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (6,'Cuando otro usuario acceda a los detalles de dicho plato y clique en URL de imagen, se mostrará la alerta con sus cookies',17)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (1,'Inicia sesión con un usuario que conozcas',18)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (2,'Accede al apartado ''Application'' en las herramientas para desarrollador',18)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (3,'En ''Session Storage'' aparecerá un atributo llamado ''rol''. Prueba a cambiar el valor a un usuario administrador introduciendo ''ADMIN''',18)",
                "INSERT INTO Paso (numero, solucion, solucionId) VALUES (4,'Ahora, tendrás permisos de administrador',18)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (4,'2022-07-01','13:30',1,4)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (8,'2022-07-30','21:30',2,3)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (5,'2022-07-01','20:30',3,2)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (6,'2022-09-10','22:00',4,5)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (10,'2022-09-15','13:00',5,1)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (2,'2022-09-16','14:30',7,1)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (2,'2022-09-17','15:00',1,1)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (3,'2022-09-18','21:15',2,2)",
                "INSERT INTO Mesa (numeroPersonas, fecha, hora, usuarioId, menuId) VALUES (7,'2022-09-19','13:30',3,1)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (1,'Tarjeta','2022-08-10','13:30','C/ Rodrigo, 2','Entregado',1,1)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (2,'Cartera digital','2022-08-19','22:00','C/ España, 23','Entregado',1,2)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (3,'Tarjeta','2022-08-30','21:00','C/ España, 23','Entregado',1,2)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (4,'Cartera digital','2022-08-30','14:00','C/ Oriente, 78','Entregado',2,3)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (5,'Tarjeta','2022-09-01','20:45','C/ Oriente, 78','Entregado',2,3)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (6,'Tarjeta','2022-09-02','14:30','C/ Tipo Pepe, 20','Entregado',3,4)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (7,'Cartera digital','2022-09-03','22:00','C/ Patin, 1','Entregado',4,5)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (8,'Tarjeta','2022-09-04','22:00','C/ Morillo, 65','Entregado',5,6)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (9,'Tarjeta','2022-09-05','21:45','C/ Ronda del Sur, 788','Entregado',6,7)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (10,'Cartera digital','2022-09-06','14:30','C/ Ronda de Oriente, 23','Entregado',7,8)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (11,'Tarjeta','2022-09-07','14:30','C/ Adriano, 124','Entregado',8,9)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (12,'Tarjeta','2022-09-08','13:30','C/ Ronda del Sur, 788','Entregado',6,7)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (13,'Cartera digital','2022-09-10','13:30','C/ Patin, 1','Entregado',4,5)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (14,'Tarjeta','2022-09-13','21:15','C/ Ronda de Oriente, 23','En transito',7,8)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (15,'Cartera digital','2022-09-14','21:15','C/ Morillo, 65','En preparacion',5,6)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (16,'Tarjeta','2022-09-15','13:00','C/ Avenida, 56','Pagado',8,10)",
                "INSERT INTO PedidoComida (id, metodoPago, fecha, hora, nombreDireccion, estado, usuarioId, direccionUsuarioId) VALUES (17,'Cartera digital','2022-09-16','13:45','C/ Oriente, 78','Pagado',2,3)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (1, 2, 1, 1)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (2, 3, 1, 2)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (3, 1, 1, 3)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (4, 1, 2, 4)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (5, 1, 2, 5)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (6, 1, 2, 6)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (7, 1, 2, 7)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (8, 1, 3, 8)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (9, 1, 3, 9)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (10, 2, 3, 10)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (11, 3, 4, 11)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (12, 1, 4, 12)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (13, 1, 4, 13)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (14, 1, 4, 14)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (15, 1, 5, 15)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (16, 1, 5, 16)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (17, 1, 6, 17)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (18, 1, 6, 18)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (19, 2, 6, 19)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (20, 3, 7, 20)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (21, 1, 7, 21)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (22, 1, 7, 22)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (23, 5, 7, 23)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (24, 1, 7, 24)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (25, 7, 8, 25)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (26, 2, 8, 26)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (27, 1, 8, 27)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (28, 2, 9, 28)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (29, 3, 9, 29)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (30, 1, 9, 30)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (31, 1, 9, 40)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (32, 3, 10, 41)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (33, 1, 10, 42)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (34, 1, 11, 43)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (35, 3, 11, 44)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (36, 1, 11, 12)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (37, 2, 11, 23)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (38, 3, 12, 42)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (39, 1, 12, 13)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (40, 1, 12, 14)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (41, 5, 13, 30)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (42, 1, 13, 39)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (43, 1, 13, 21)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (44, 3, 14, 31)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (45, 1, 14, 15)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (46, 2, 15, 18)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (47, 3, 15, 33)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (48, 1, 16, 20)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (49, 4, 16, 26)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (50, 2, 16, 19)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (51, 1, 17, 25)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (52, 2, 17, 21)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (53, 1, 17, 2)",
                "INSERT INTO ProductoPedido (id, cantidad, pedidoId, productoOfertadoId) VALUES (54, 3, 17, 5)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (1, 4,'Bueno','perico','Hamburguesa especial',1,1)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (2, 2,'Malo','perico','Pizza',1,2)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (3, 3,'Mediocre','perico','Ensalada',1,4)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (4, 5,'Muy bueno','perico','Churrasco',1,7)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (5, 1,'Para tirarlo','josrompoz1','Sushi',2,9)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (6, 5,'Espectacular','josrompoz1','Patatas fritas',2,15)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (7, 5,'Increible','aitor','Churros con chocolate',3,17)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (8, 5,'De locos','aitor','Paella',3,19)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (9, 4,'Bastante bien','admin','Salmon',4,20)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (10, 2,'Malisimo','admin','Sandwich',4,23)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (11, 3,'Mas o menos','admin','Empanadas',4,24)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (12, 4,'Muy bueno','user5','Café',5,26)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (13, 4,'Bueno','user5','Aliño de pulpo',5,27)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (14, 2,'Malo','user6','Refresco',6,29)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (15, 3,'Mediocre','user6','Kebap',6,30)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (16, 1,'Muy bueno','user7','Bocadillo',7,32)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (17, 4,'Bueno','user8','Pancakes',8,34)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (18, 2,'Malo','user6','Burrito mejicano',6,39)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (19, 1,'Mediocre','user7','Patatas fritas',7,45)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (20, 5,'Increible','user8','Café',8,49)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (21, 4,'Bueno','josrompoz1','Coctel',2,51)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (22, 1,'Malo','josrompoz1','Tarta de queso',2,52)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (23, 3,'Mediocre','josrompoz1','Pizza',2,53)",
                "INSERT INTO Valoracion (id, puntuacion, resenya, nombreUsuario, nombreProducto, usuarioId, productoPedidoId) VALUES (24, 4,'Muy bueno','josrompoz1','Hamburguesa completa',2,54)"];
  queries.forEach(function(q) {
    connection.query(q, function (err, result) {
      if(err) throw err;
    });
  });
  console.log("Tables created!");
});

const port = process.env.PORT || 8080;

const app = express()
  .use(cors())
  .use(bodyParser.json())
  .use(productos(connection))
  .use(usuarios(connection))
  .use(cupones(connection))
  .use(retos(connection))
  .use(mesas(connection))
  .use(pedidos(connection))
  .use(valoraciones(connection))
  .use(login(connection));

app.listen(port, () => {
  console.log(`Express server listening on port ${port}`);
});